version: "3.7"

services:

  php:
    container_name: geo-php
    build: docker/php
    environment:
      - DEBUG=1
    working_dir: /var/www/geo
    volumes:
      - ./:/var/www/geo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: geo-nginx
    build: docker/nginx
    links:
      - php
    ports:
      - "3200:80"
    working_dir: /var/www/geo
    volumes:
      - ./:/var/www/geo
